<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PrivateServer.NetworkRuntime.Managed\PrivateServer.NetworkRuntime.Managed.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <NativeRuntimeBinDir>$(MSBuildThisFileDirectory)..\..\build\bin\NetworkRuntime\x64\$(Configuration)\</NativeRuntimeBinDir>
  </PropertyGroup>

  <Target Name="CopyNativeRuntimeDependencies" AfterTargets="Build">
    <ItemGroup>
      <NativeRuntimeDependency Include="$(NativeRuntimeBinDir)PrivateServer.NetworkRuntime.CAbi.dll" />
      <NativeRuntimeDependency Include="$(NativeRuntimeBinDir)PrivateServer.NetworkRuntime.dll" />
    </ItemGroup>
    <Copy SourceFiles="@(NativeRuntimeDependency)" DestinationFolder="$(TargetDir)" />
  </Target>

</Project>
